In [5]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

C:\Users\sinch\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [6]:
!pip install textblob

Requirement already satisfied: textblob in c:\users\sinch\anaconda3\lib\site-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in c:\users\sinch\anaconda3\lib\site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in c:\users\sinch\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (8.0.4)
Requirement already satisfied: joblib in c:\users\sinch\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\sinch\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (2022.7.9)
Requirement already satisfied: tqdm in c:\users\sinch\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (4.65.0)
Requirement already satisfied: colorama in c:\users\sinch\anaconda3\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)

In [7]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\sinch/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [9]:
import pandas as pd
import numpy as np

#for NLP text processing and formatting

import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


# For word lemmitization
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer 
# for word Stemming
nltk.download('omw-1.4')
from nltk.stem.porter import PorterStemmer

# for Machine Learning process

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from textblob import TextBlob
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.metrics import mean_squared_error, mean_absolute_error

# Global Parameters
stop_words = set(stopwords.words('english'))

from wordcloud import WordCloud

import matplotlib.pyplot as plt
%matplotlib inline

# from autosklearn.regression import AutoSklearnRegressor

import plotly.graph_objs as go
from plotly.subplots import make_subplots
from plotly.offline import init_notebook_mode, iplot#for data wrangling and manipulation

import pandas as pd
import numpy as np
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


# For word lemmitization
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer 
# for word Stemming
nltk.download('omw-1.4')
from nltk.stem.porter import PorterStemmer

# for Machine Learning process

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from textblob import TextBlob
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.metrics import mean_squared_error, mean_absolute_error

# Global Parameters
stop_words = set(stopwords.words('english'))

from wordcloud import WordCloud

import matplotlib.pyplot as plt
%matplotlib inline

# from autosklearn.regression import AutoSklearnRegressor

import plotly.graph_objs as go
from plotly.subplots import make_subplots
from plotly.offline import init_notebook_mode, iplot

[nltk_data] Downloading package omw-1.4 to C:\Users\sinch/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\sinch/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [10]:
!pip install wordcloud

Requirement already satisfied: wordcloud in c:\users\sinch\anaconda3\lib\site-packages (1.9.4)
Requirement already satisfied: numpy>=1.6.1 in c:\users\sinch\anaconda3\lib\site-packages (from wordcloud) (1.26.4)
Requirement already satisfied: pillow in c:\users\sinch\anaconda3\lib\site-packages (from wordcloud) (9.4.0)
Requirement already satisfied: matplotlib in c:\users\sinch\anaconda3\lib\site-packages (from wordcloud) (3.7.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sinch\anaconda3\lib\site-packages (from matplotlib->wordcloud) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\users\sinch\anaconda3\lib\site-packages (from matplotlib->wordcloud) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sinch\anaconda3\lib\site-packages (from matplotlib->wordcloud) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\sinch\anaconda3\lib\site-packages (from matplotlib->wordcloud) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\sinch\anaconda3\lib\site-packages (from matplotlib->wordcloud) (24.2)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\sinch\anaconda3\lib\site-packages (from matplotlib->wordcloud) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\sinch\anaconda3\lib\site-packages (from matplotlib->wordcloud) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\sinch\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)

In [11]:
from wordcloud import WordCloud

In [12]:
import pandas as pd
import numpy as np

#for NLP text processing and formatting

import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


# For word lemmitization
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer 
# for word Stemming
nltk.download('omw-1.4')
from nltk.stem.porter import PorterStemmer

# for Machine Learning process

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from textblob import TextBlob
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.metrics import mean_squared_error, mean_absolute_error

# Global Parameters
stop_words = set(stopwords.words('english'))

from wordcloud import WordCloud

import matplotlib.pyplot as plt
%matplotlib inline

# from autosklearn.regression import AutoSklearnRegressor

import plotly.graph_objs as go
from plotly.subplots import make_subplots
from plotly.offline import init_notebook_mode, iplot#for data wrangling and manipulation

import pandas as pd
import numpy as np
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


# For word lemmitization
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer 
# for word Stemming
nltk.download('omw-1.4')
from nltk.stem.porter import PorterStemmer

# for Machine Learning process

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from textblob import TextBlob
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.metrics import mean_squared_error, mean_absolute_error

# Global Parameters
stop_words = set(stopwords.words('english'))

from wordcloud import WordCloud

import matplotlib.pyplot as plt
%matplotlib inline

# from autosklearn.regression import AutoSklearnRegressor

import plotly.graph_objs as go
from plotly.subplots import make_subplots
from plotly.offline import init_notebook_mode, iplot

[nltk_data] Downloading package omw-1.4 to C:\Users\sinch/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\sinch/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [13]:
df = pd.read_csv("amazon_reviews.csv")

In [14]:
import os
os.getcwd()

'C:\\Users\\sinch'

In [15]:
df.head()

,Unnamed: 0,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
0,0,NaN,4.0,No issues.,2014-07-23,138,0,0,0,0,0.0,0.0
1,1,0mie,5.0,"Purchased this for my device, it worked as adv...",2013-10-25,409,0,0,0,0,0.0,0.0
2,2,1K3,4.0,it works as expected. I should have sprung for...,2012-12-23,715,0,0,0,0,0.0,0.0
3,3,1m2,5.0,This think has worked out great.Had a diff. br...,2013-11-21,382,0,0,0,0,0.0,0.0
4,4,2&amp;1/2Men,5.0,"Bought it with Retail Packaging, arrived legit...",2013-07-13,513,0,0,0,0,0.0,0.0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4915 entries, 0 to 4914
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            4915 non-null   int64
 1   reviewerName          4914 non-null   object
 2   overall               4915 non-null   float64
 3   reviewText            4914 non-null   object
 4   reviewTime            4915 non-null   object
 5   day_diff              4915 non-null   int64
 6   helpful_yes           4915 non-null   int64
 7   helpful_no            4915 non-null   int64
 8   total_vote            4915 non-null   int64
 9   score_pos_neg_diff    4915 non-null   int64
 10  score_average_rating  4915 non-null   float64
 11  wilson_lower_bound    4915 non-null   float64
dtypes: float64(3), int64(6), object(3)
memory usage: 460.9+ KB

In [17]:
df.describe()

,Unnamed: 0,overall,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
count,4915.000000,4915.000000,4915.000000,4915.000000,4915.000000,4915.000000,4915.000000,4915.000000,4915.000000
mean,2457.000000,4.587589,437.367040,1.311089,0.210376,1.521465,1.100712,0.075468,0.020053
std,1418.982617,0.996845,209.439871,41.619161,4.023296,44.123095,39.367949,0.256062,0.077187
min,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,-130.000000,0.000000,0.000000
25%,1228.500000,5.000000,281.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2457.000000,5.000000,431.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3685.500000,5.000000,601.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,4914.000000,5.000000,1064.000000,1952.000000,183.000000,2020.000000,1884.000000,1.000000,0.957544

In [18]:
df.isnull().any()

Unnamed: 0              False
reviewerName             True
overall                 False
reviewText               True
reviewTime              False
day_diff                False
helpful_yes             False
helpful_no              False
total_vote              False
score_pos_neg_diff      False
score_average_rating    False
wilson_lower_bound      False
dtype: bool

In [19]:
df.dropna(inplace = True)
df.head()

,Unnamed: 0,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
1,1,0mie,5.0,"Purchased this for my device, it worked as adv...",2013-10-25,409,0,0,0,0,0.0,0.0
2,2,1K3,4.0,it works as expected. I should have sprung for...,2012-12-23,715,0,0,0,0,0.0,0.0
3,3,1m2,5.0,This think has worked out great.Had a diff. br...,2013-11-21,382,0,0,0,0,0.0,0.0
4,4,2&amp;1/2Men,5.0,"Bought it with Retail Packaging, arrived legit...",2013-07-13,513,0,0,0,0,0.0,0.0
5,5,2Cents!,5.0,It's mini storage. It doesn't do anything els...,2013-04-29,588,0,0,0,0,0.0,0.0

In [20]:
df.count()

Unnamed: 0              4913
reviewerName            4913
overall                 4913
reviewText              4913
reviewTime              4913
day_diff                4913
helpful_yes             4913
helpful_no              4913
total_vote              4913
score_pos_neg_diff      4913
score_average_rating    4913
wilson_lower_bound      4913
dtype: int64

In [21]:
print("Before {}".format(len(df)))
dataAfter = df.dropna(subset=["overall"]) # removes all NAN in reviews.rating
print("After {}".format(len(dataAfter)))
dataAfter["overall"] = dataAfter["overall"].astype(int)

Before 4913
After 4913

In [22]:
split = StratifiedShuffleSplit(n_splits=5, test_size=0.2)
for train_index, test_index in split.split(dataAfter, dataAfter["overall"]): 
    start_train = dataAfter.reindex(train_index)
    start_test = dataAfter.reindex(test_index)

In [23]:
reviews = start_train.copy()
reviews.head()

,Unnamed: 0,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
2120,2120.0,"James H. Haight ""happy iMac user""",5.0,I am always perfectly satisfied with SanDisk p...,2012-09-12,817.0,0.0,2.0,2.0,-2.0,0.0,0.0
3226,3226.0,mikhailcharon,5.0,Sandisk has made great memory products for a v...,2013-03-14,634.0,0.0,0.0,0.0,0.0,0.0,0.0
143,143.0,"Ali Etezadkhah ""Ali""",1.0,I have an old SanDisk SD card that still works...,2013-06-22,534.0,0.0,0.0,0.0,0.0,0.0,0.0
1257,1257.0,D. Blackman,4.0,"No complaints matched description, was deliver...",2013-10-25,409.0,0.0,0.0,0.0,0.0,0.0,0.0
452,452.0,a raccoon,5.0,No Samsung Galaxy S3 should be without one! T...,2013-02-16,660.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
reviews.dtypes

Unnamed: 0              float64
reviewerName             object
overall                 float64
reviewText               object
reviewTime               object
day_diff                float64
helpful_yes             float64
helpful_no              float64
total_vote              float64
score_pos_neg_diff      float64
score_average_rating    float64
wilson_lower_bound      float64
dtype: object

In [27]:
numeric_reviews = reviews.select_dtypes(include=[np.number])
corr_matrix = numeric_reviews.corr()

In [28]:
numeric_reviews = numeric_reviews.dropna()

In [29]:
numeric_reviews = numeric_reviews.fillna(numeric_reviews.mean())

In [31]:
corr_matrix = numeric_reviews.corr()
print(corr_matrix)

                      Unnamed: 0   overall  day_diff  helpful_yes  helpful_no  \
Unnamed: 0              1.000000 -0.008626 -0.015944     0.005223    0.015272
overall                -0.008626  1.000000 -0.085139     0.005836   -0.038270
day_diff               -0.015944 -0.085139  1.000000     0.036217    0.023281
helpful_yes             0.005223  0.005836  0.036217     1.000000    0.496224
helpful_no              0.015272 -0.038270  0.023281     0.496224    1.000000
total_vote              0.006282  0.002337  0.036568     0.997297    0.558668
score_pos_neg_diff      0.004035  0.009619  0.035610     0.996780    0.425011
score_average_rating   -0.003153 -0.150947  0.133272     0.094544    0.072104
wilson_lower_bound      0.004875 -0.121088  0.137704     0.312455    0.228782

                      total_vote  score_pos_neg_diff  score_average_rating  \
Unnamed: 0              0.006282            0.004035             -0.003153
overall                 0.002337            0.009619             -0.150947
day_diff                0.036568            0.035610              0.133272
helpful_yes             0.997297            0.996780              0.094544
helpful_no              0.558668            0.425011              0.072104
total_vote              1.000000            0.988195              0.096420
score_pos_neg_diff      0.988195            1.000000              0.091913
score_average_rating    0.096420            0.091913              1.000000
wilson_lower_bound      0.317850            0.304639              0.884324

                      wilson_lower_bound
Unnamed: 0                      0.004875
overall                        -0.121088
day_diff                        0.137704
helpful_yes                     0.312455
helpful_no                      0.228782
total_vote                      0.317850
score_pos_neg_diff              0.304639
score_average_rating            0.884324
wilson_lower_bound              1.000000

In [32]:
# Check the data types of the columns
print(reviews.dtypes)

# Filter out only numeric columns
numeric_reviews = reviews.select_dtypes(include=[np.number])

# Handle missing values (optional)
numeric_reviews = numeric_reviews.dropna()  # or use fillna()

# Compute the correlation matrix
corr_matrix = numeric_reviews.corr()
print(corr_matrix)

Unnamed: 0              float64
reviewerName             object
overall                 float64
reviewText               object
reviewTime               object
day_diff                float64
helpful_yes             float64
helpful_no              float64
total_vote              float64
score_pos_neg_diff      float64
score_average_rating    float64
wilson_lower_bound      float64
dtype: object
                      Unnamed: 0   overall  day_diff  helpful_yes  helpful_no  \
Unnamed: 0              1.000000 -0.008626 -0.015944     0.005223    0.015272
overall                -0.008626  1.000000 -0.085139     0.005836   -0.038270
day_diff               -0.015944 -0.085139  1.000000     0.036217    0.023281
helpful_yes             0.005223  0.005836  0.036217     1.000000    0.496224
helpful_no              0.015272 -0.038270  0.023281     0.496224    1.000000
total_vote              0.006282  0.002337  0.036568     0.997297    0.558668
score_pos_neg_diff      0.004035  0.009619  0.035610     0.996780    0.425011
score_average_rating   -0.003153 -0.150947  0.133272     0.094544    0.072104
wilson_lower_bound      0.004875 -0.121088  0.137704     0.312455    0.228782

                      total_vote  score_pos_neg_diff  score_average_rating  \
Unnamed: 0              0.006282            0.004035             -0.003153
overall                 0.002337            0.009619             -0.150947
day_diff                0.036568            0.035610              0.133272
helpful_yes             0.997297            0.996780              0.094544
helpful_no              0.558668            0.425011              0.072104
total_vote              1.000000            0.988195              0.096420
score_pos_neg_diff      0.988195            1.000000              0.091913
score_average_rating    0.096420            0.091913              1.000000
wilson_lower_bound      0.317850            0.304639              0.884324

                      wilson_lower_bound
Unnamed: 0                      0.004875
overall                        -0.121088
day_diff                        0.137704
helpful_yes                     0.312455
helpful_no                      0.228782
total_vote                      0.317850
score_pos_neg_diff              0.304639
score_average_rating            0.884324
wilson_lower_bound              1.000000

In [34]:
def sentiments(rating):
    if (rating == 5) or (rating == 4):
        return "Positive"
    elif rating == 3:
        return "Neutral"
    elif (rating == 2) or (rating == 1) or (rating == 0):
        return "Negative"
# Add sentiments to the data
start_train["Sentiment"] = start_train["overall"].apply(sentiments)
start_test["Sentiment"] = start_test["overall"].apply(sentiments)
start_train["Sentiment"][:20]

2120    Positive
3226    Positive
143     Negative
1257    Positive
452     Positive
2165    Positive
4790    Positive
1604    Positive
23      Positive
1322    Positive
4697    Positive
3723    Positive
2247    Positive
3704    Positive
2695    Positive
1902    Positive
1361    Positive
3270    Positive
2903    Positive
2779    Positive
Name: Sentiment, dtype: object

In [35]:
review=df[['reviewText','overall']]
review.head()

                                          reviewText  overall
1  Purchased this for my device, it worked as adv...      5.0
2  it works as expected. I should have sprung for...      4.0
3  This think has worked out great.Had a diff. br...      5.0
4  Bought it with Retail Packaging, arrived legit...      5.0
5  It's mini storage.  It doesn't do anything els...      5.0

In [36]:
round(review.isnull().sum().sort_values(ascending=False)*100/len(review),2)

reviewText    0.0
overall       0.0
dtype: float64

In [37]:
review=review.dropna()
review.head()

                                          reviewText  overall
1  Purchased this for my device, it worked as adv...      5.0
2  it works as expected. I should have sprung for...      4.0
3  This think has worked out great.Had a diff. br...      5.0
4  Bought it with Retail Packaging, arrived legit...      5.0
5  It's mini storage.  It doesn't do anything els...      5.0

In [38]:
review['encoded_cat'] = review.overall.astype('category').cat.codes
review.head()

                                          reviewText  overall  encoded_cat
1  Purchased this for my device, it worked as adv...      5.0            4
2  it works as expected. I should have sprung for...      4.0            3
3  This think has worked out great.Had a diff. br...      5.0            4
4  Bought it with Retail Packaging, arrived legit...      5.0            4
5  It's mini storage.  It doesn't do anything els...      5.0            4

In [39]:
def preprocess_review_text(review):
    """
    Function to process the the review text and transform it into format usable by Machine learning models
    """
    
    # to convert all the characters of the review into lower case alphabets
    review.lower()
    
    # Remove urls from the reviews
    review = re.sub(r"http\S+|www\S+|https\S+", '', review, flags=re.MULTILINE)
    
    # Remove user related references from the reviews:: '@' and '#' 
    review = re.sub(r'\@\w+|\#','', review)
    
    # Remove punctuations from the reviews
    review = review.translate(str.maketrans('', '', string.punctuation))
    
    # Remove stopwords from the reviews
    review_tokens = word_tokenize(review)
    filtered_words = [w for w in review_tokens if not w in stop_words]
    joined_text = " ".join(filtered_words)
    
    return joined_text

In [40]:
def get_feature_vector(train_fit):
    """
    Function to Convert a collection of raw documents to a matrix of TF-IDF features.
    TF-IDF - Term Frequency Inverse Documnet Frequency
    """
    
    vector = TfidfVectorizer(sublinear_tf=True)      # Defining the vector
    vector.fit(train_fit)                            # fitting the data into the vector
    return vector

In [41]:
processed_text = df['reviewText'].apply(preprocess_review_text)

print("Processed text :: \n\n", processed_text)

Processed text ::

 1       Purchased device worked advertised You never m...
2       works expected I sprung higher capacity I thin...
3       This think worked greatHad diff bran 64gb card...
4       Bought Retail Packaging arrived legit orange e...
5       Its mini storage It doesnt anything else suppo...
                              ...
4910    I bought Sandisk 16GB Class 10 use HTC Inspire...
4911    Used extending capabilities Samsung Galaxy Not...
4912    Great card fast reliable It comes optional ada...
4913    Good amount space stuff I want fits GoPro What...
4914    Ive heard bad things 64gb Micro SD card crappi...
Name: reviewText, Length: 4913, dtype: object

In [45]:
import nltk

# Download WordNet and stopwords if not already done
nltk.download('wordnet')
nltk.download('omw-1.4')  # For additional WordNet languages
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to C:\Users\sinch/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\sinch/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sinch/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\sinch/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [46]:
import nltk
print(nltk.data.path)

['C:\\Users\\sinch/nltk_data', 'C:\\Users\\sinch\\anaconda3\\nltk_data', 'C:\\Users\\sinch\\anaconda3\\share\\nltk_data', 'C:\\Users\\sinch\\anaconda3\\lib\\nltk_data', 'C:\\Users\\sinch\\AppData\\Roaming\\nltk_data', 'C:\\nltk_data', 'D:\\nltk_data', 'E:\\nltk_data']

In [48]:
import nltk
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to C:\Users\sinch/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [54]:
def lemmatize(self,word:str,pos:str="n") -> str:
    """Lemmatize `word` by picking the shortest of the possible lemmas,
   using the wordnet corpus reader's built-in _morphy function.
   Returns the input word unchanged if it cannot be found in WordNet.
   :return: The shortest lemma of `word`, for the given `pos`.
   """
    lemmas = self._morphy(word, pos)
    return min(lemmas, key=len) if lemmas else word

In [63]:
"""
     _morphy() is WordNet's _morphy lemmatizer.
     It returns a list of all lemmas found in WordNet.
   
     ['us', 'u']
    """

"\n     _morphy() is WordNet's _morphy lemmatizer.\n     It returns a list of all lemmas found in WordNet.\n   \n     ['us', 'u']\n    "

In [69]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to C:\Users\sinch/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\sinch/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [70]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()
print(lemmatizer.lemmatize("better", pos='a'))  # should print 'good'

[nltk_data] Downloading package wordnet to C:\Users\sinch/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\sinch/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

good

In [71]:
stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(i) for i in processed_text]
lemmatizer = WordNetLemmatizer()
lemma_words = [lemmatizer.lemmatize(w, pos='a') for w in stemmed_words]
tf_vector = get_feature_vector(np.array(df["reviewText"]).ravel())
X = tf_vector.transform(np.array(review["reviewText"]).ravel())     # Predictor Variable
y = np.array(review["encoded_cat"]).ravel()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=30)
NB_model = MultinomialNB()

NB_model.fit(X_train, y_train)

MultinomialNB()

In [72]:
y_predict_nb = NB_model.predict(X_test)

print("Accuracy Score for Naive Bayes Model is :: ", accuracy_score(y_test, y_predict_nb))

Accuracy Score for Naive Bayes Model is ::  0.7863682604272635

In [73]:
round(df['overall'].value_counts()*100/len(df),2)
df = df.sort_values("wilson_lower_bound", ascending=False)
df.drop('Unnamed: 0', inplace = True, axis = 1)
df.head()

,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
2031,"Hyoun Kim ""Faluzure""",5.0,[[ UPDATE - 6/19/2014 ]]So my lovely wife boug...,2013-01-05,702,1952,68,2020,1884,0.966337,0.957544
3449,NLee the Engineer,5.0,I have tested dozens of SDHC and micro-SDHC ca...,2012-09-26,803,1428,77,1505,1351,0.948837,0.936519
4212,SkincareCEO,1.0,NOTE: please read the last update (scroll to ...,2013-05-08,579,1568,126,1694,1442,0.925620,0.912139
317,"Amazon Customer ""Kelly""",1.0,"If your card gets hot enough to be painful, it...",2012-02-09,1033,422,73,495,349,0.852525,0.818577
4672,Twister,5.0,Sandisk announcement of the first 128GB micro ...,2014-07-03,158,45,4,49,41,0.918367,0.808109

In [84]:
def missing_values_analysis(df):
    na_columns_ = [col for col in df.columns if df[col].isnull().sum() > 0]
    n_miss = df[na_columns_].isnull().sum().sort_values(ascending=True)
    ratio_ = (df[na_columns_].isnull().sum() / df.shape[0] * 100).sort_values(ascending=True)
    missing_df = pd.concat([n_miss, np.round(ratio_, 2)], axis=1, keys=['Total Missing Values', 'Ratio'])
    missing_df = pd.DataFrame(missing_df)
    return missing_df

def check_dataframe(df, head=5, tail = 5):
    
    print(" SHAPE ".center(82,'~'))
    print('Rows: {}'.format(df.shape[0]))
    print('Columns: {}'.format(df.shape[1]))
    print(" TYPES ".center(82,'~'))
    print(df.dtypes)
    print("".center(82,'~'))
    print(missing_values_analysis(df))
    print(' DUPLICATED VALUES '.center(83,'~'))
    print(df.duplicated().sum())
    print(" QUANTILES ".center(82,'~'))
    print(df.select_dtypes(include=['number']).quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)

check_dataframe(df)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SHAPE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Rows: 4913
Columns: 13
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TYPES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reviewerName             object
overall                 float64
reviewText               object
reviewTime               object
day_diff                  int64
helpful_yes               int64
helpful_no                int64
total_vote                int64
score_pos_neg_diff        int64
score_average_rating    float64
wilson_lower_bound      float64
polarity                float64
subjectivity            float64
dtype: object
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Empty DataFrame
Columns: [Total Missing Values, Ratio]
Index: []
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ DUPLICATED VALUES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ QUANTILES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       0.00     0.05        0.50        0.95       0.99  \
overall                 1.0   2.0000    5.000000    5.000000    5.00000
day_diff                1.0  98.0000  431.000000  747.400000  943.00000
helpful_yes             0.0   0.0000    0.000000    1.000000    3.00000
helpful_no              0.0   0.0000    0.000000    0.000000    2.00000
total_vote              0.0   0.0000    0.000000    1.000000    4.00000
score_pos_neg_diff   -130.0   0.0000    0.000000    1.000000    2.00000
score_average_rating    0.0   0.0000    0.000000    1.000000    1.00000
wilson_lower_bound      0.0   0.0000    0.000000    0.206549    0.34238
polarity               -1.0  -0.0877    0.250000    0.800000    1.00000
subjectivity            0.0   0.1750    0.541667    0.859444    1.00000

                             1.00
overall                  5.000000
day_diff              1064.000000
helpful_yes           1952.000000
helpful_no             183.000000
total_vote            2020.000000
score_pos_neg_diff    1884.000000
score_average_rating     1.000000
wilson_lower_bound       0.957544
polarity                 1.000000
subjectivity             1.000000

In [85]:
def check_class(dataframe):
    nunique_df = pd.DataFrame({'Variable': dataframe.columns,
                               'Classes': [dataframe[i].nunique() \
                                           for i in dataframe.columns]})

    nunique_df = nunique_df.sort_values('Classes', ascending=False)
    nunique_df = nunique_df.reset_index(drop = True)
    return nunique_df

check_class(df)

                Variable  Classes
0             reviewText     4912
1           reviewerName     4593
2               polarity     2217
3           subjectivity     1996
4             reviewTime      689
5               day_diff      689
6     wilson_lower_bound       40
7   score_average_rating       28
8     score_pos_neg_diff       27
9             total_vote       26
10           helpful_yes       23
11            helpful_no       17
12               overall        5

In [86]:
constraints = ['#581845','#C70039','#2E4053','#1ABC9C','#7F8C8D']

def categorical_variable_summary(df, column_name):
    fig = make_subplots(rows=1,cols=2,
                        subplot_titles=('Countplot','Percentages'),
                        specs=[[{"type": "xy"}, {'type':'domain'}]])

    fig.add_trace(go.Bar( y = df[column_name].value_counts().values.tolist(), 
                          x = [str(i) for i in df[column_name].value_counts().index], 
                          text = df[column_name].value_counts().values.tolist(),
                          textfont = dict(size=15),
                          name = column_name,
                          textposition = 'auto',
                          showlegend=False,
                          marker=dict(color = constraints,
                                      line=dict(color='#DBE6EC',
                                                width=1))),
                  row = 1, col = 1)
    
    fig.add_trace(go.Pie(labels= df[column_name].value_counts().keys(),
                         values= df[column_name].value_counts().values,
                         textfont = dict(size = 20),
                         textposition='auto',
                         showlegend = False,
                         name = column_name,
                         marker=dict(colors=constraints)),
                  row = 1, col = 2)
    
    fig.update_layout(title={'text': column_name,
                             'y':0.9,
                             'x':0.5,
                             'xanchor': 'center',
                             'yanchor': 'top'},
                      template='plotly_white')
    
    iplot(fig)

In [87]:
example_review = df.reviewText[2031]

In [88]:
example_review = re.sub("[^a-zA-Z]",' ',example_review)

In [89]:
example_review = example_review.lower().split()

In [90]:
rt = lambda x: re.sub("[^a-zA-Z]",' ',str(x))
df["reviewText"] = df["reviewText"].map(rt)
df["reviewText"] = df["reviewText"].str.lower()
df.head(10)

,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound,polarity,subjectivity
2031,"Hyoun Kim ""Faluzure""",5.0,update so my lovely wife boug...,2013-01-05,702,1952,68,2020,1884,0.966337,0.957544,0.163859,0.562259
3449,NLee the Engineer,5.0,i have tested dozens of sdhc and micro sdhc ca...,2012-09-26,803,1428,77,1505,1351,0.948837,0.936519,0.103870,0.516435
4212,SkincareCEO,1.0,note please read the last update scroll to ...,2013-05-08,579,1568,126,1694,1442,0.925620,0.912139,0.212251,0.505394
317,"Amazon Customer ""Kelly""",1.0,if your card gets hot enough to be painful it...,2012-02-09,1033,422,73,495,349,0.852525,0.818577,0.143519,0.494207
4672,Twister,5.0,sandisk announcement of the first gb micro ...,2014-07-03,158,45,4,49,41,0.918367,0.808109,0.172332,0.511282
1835,goconfigure,5.0,bought from bestbuy online the day it was anno...,2014-02-28,283,60,8,68,52,0.882353,0.784651,0.386111,0.616667
3981,"R. Sutton, Jr. ""RWSynergy""",5.0,the last few days i have been diligently shopp...,2012-10-22,777,112,27,139,85,0.805755,0.732136,0.070466,0.445756
3807,R. Heisler,3.0,i bought this card to replace a lost gig in...,2013-02-27,649,22,3,25,19,0.880000,0.700442,0.194643,0.675000
4306,Stellar Eller,5.0,while i got this card as a deal of the day o...,2012-09-06,823,51,14,65,37,0.784615,0.670334,0.217172,0.503535
4596,"Tom Henriksen ""Doggy Diner""",1.0,hi i ordered two card and they arrived the nex...,2012-09-22,807,82,27,109,55,0.752294,0.663595,0.088242,0.452143

In [ ]:
df[df["sentiment"] == "Positive"].sort_values("wilson_lower_bound", ascending=False).head(5)

In [96]:
!pip install vaderSentiment

Collecting vaderSentiment
  Obtaining dependency information for vaderSentiment from https://files.pythonhosted.org/packages/76/fc/310e16254683c1ed35eeb97386986d6c00bc29df17ce280aed64d55537e9/vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in c:\users\sinch\anaconda3\lib\site-packages (from vaderSentiment) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sinch\anaconda3\lib\site-packages (from requests->vaderSentiment) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sinch\anaconda3\lib\site-packages (from requests->vaderSentiment) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sinch\anaconda3\lib\site-packages (from requests->vaderSentiment) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sinch\anaconda3\lib\site-packages (from requests->vaderSentiment) (2025.1.31)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ---------------------------------------- 0.0/126.0 kB ? eta -:--:--
   ---------------------- ----------------- 71.7/126.0 kB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 126.0/126.0 kB 1.2 MB/s eta 0:00:00
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [97]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [98]:
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Add polarity and subjectivity using TextBlob
df[['polarity', 'subjectivity']] = df['reviewText'].apply(lambda Text: pd.Series(TextBlob(Text).sentiment))

# Add VADER sentiment
analyzer = SentimentIntensityAnalyzer()

for index, row in df['reviewText'].items():  # <-- fixed this line
    score = analyzer.polarity_scores(row)
    neg = score['neg']
    neu = score['neu']
    pos = score['pos']
    
    if neg > pos:
        df.loc[index, 'sentiment'] = "Negative"
    elif pos > neg:
        df.loc[index, 'sentiment'] = "Positive"
    else:
        df.loc[index, 'sentiment'] = "Neutral"  # <-- fixed the typo here too ("neutral". should be "Neutral")

In [99]:
df[df["sentiment"] == "Positive"].sort_values("wilson_lower_bound", ascending=False).head(5)

,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound,polarity,subjectivity,sentiment
2031,"Hyoun Kim ""Faluzure""",5.0,update so my lovely wife boug...,2013-01-05,702,1952,68,2020,1884,0.966337,0.957544,0.163859,0.562259,Positive
3449,NLee the Engineer,5.0,i have tested dozens of sdhc and micro sdhc ca...,2012-09-26,803,1428,77,1505,1351,0.948837,0.936519,0.103870,0.516435,Positive
4212,SkincareCEO,1.0,note please read the last update scroll to ...,2013-05-08,579,1568,126,1694,1442,0.925620,0.912139,0.212251,0.505394,Positive
317,"Amazon Customer ""Kelly""",1.0,if your card gets hot enough to be painful it...,2012-02-09,1033,422,73,495,349,0.852525,0.818577,0.143519,0.494207,Positive
4672,Twister,5.0,sandisk announcement of the first gb micro ...,2014-07-03,158,45,4,49,41,0.918367,0.808109,0.172332,0.511282,Positive

In [100]:
df.groupby(["sentiment"])[['overall']].mean()

            overall
sentiment
Negative   3.608087
Neutral    4.688645
Positive   4.738304